### ISSUE TITLE
SSLEngine test failures on F36.

### ISSUE THREAD

**Issue by ckelleyRH** [dogtagpki/jss#861]
On `F36` the following tests fail on-build for `JSS`:
```
SSLEngine_RSA (Failed)
SSLEngine_ECDSA (Failed)
SSLEngine_RSA_FIPSMODE (Failed)
SSLEngine_ECDSA_FIPSMODE (Failed)
```
They all passed on `F35`.

To reproduce simply do `./build.sh --with-tests` on `F36`, the same will succeed on F35.

An example failure is [here](https://github.com/dogtagpki/jss/runs/6554625304?check_suite_focus=true).

Stacktrace (it is the same for all failures):
```
73/77 Test #73: SSLEngine_ECDSA_FIPSMODE ..........................***Failed    0.21 sec
Initializing CryptoManager...
May 23, 2022 11:55:45 AM org.mozilla.jss.CryptoManager initialize
INFO: JSS CryptoManager: successfully initialized from NSS database at /github/home/build/jss/results/fips
Exception in thread "main" java.security.NoSuchProviderException: no such provider: SunJSSE
	at java.base/sun.security.jca.GetInstance.getService(GetInstance.java:83)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:230)
	at org.mozilla.jss.tests.TestSSLEngine.sizeBuffers(TestSSLEngine.java:210)
	at org.mozilla.jss.tests.TestSSLEngine.initialize(TestSSLEngine.java:47)
	at org.mozilla.jss.tests.TestSSLEngine.main(TestSSLEngine.java:1014)
```
A quick read of the [source](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/javax/net/ssl/SSLContext.java#L190-L233) suggests that, for whatever reason, the `SunJSSE` provider is no longer being added to the list of registered providers whereas it was previously.

**Comment by edewata** [comment]
It's reported on Debian too:
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1855971.html

**Comment by ckelleyRH** [comment]
In #864 I discovered that the issue only arises with OpenJDK 17. By migrating the Azure pipelines to use Java 17 I made them susceptible to this bug.
