### ISSUE TITLE
Incompatibilities with NSS 3.81

### ISSUE THREAD

**Issue by edewata** [dogtagpki/jss#882]
Multiple tests have failed since NSS 3.81 was released in Fedora. [Downgrading to NSS 3.77](https://github.com/dogtagpki/jss/pull/883) seems to fix the problems.

https://github.com/dogtagpki/jss/runs/7506244588?check_suite_focus=true#step:7:2239
```
35/77 Test #35: SSLClientAuth .....................................***Failed    6.81 sec
Jul 25, 2022 6:27:06 PM org.mozilla.jss.CryptoManager initialize
INFO: JSS CryptoManager: successfully initialized from NSS database at /github/home/build/jss/results/nssdb
***FilePasswordCallback returns m1oZilla
using port:2876
Server about to create socket
Server created socket
Server specified cert directly
Server about to accept
client about to connect
Client specified cert directly
client connected
Server accepted
Server about to read
Error: Exception in thread "main" org.mozilla.jss.ssl.SSLSocketException: SSL_ForceHandshake failed: (-8010) Unknown error
	at org.mozilla.jss.ssl.SSLSocket.forceHandshake(Native Method)
	at org.mozilla.jss.tests.SSLClientAuth.testConnection(SSLClientAuth.java:372)
	at org.mozilla.jss.tests.SSLClientAuth.doIt(SSLClientAuth.java:183)
	at org.mozilla.jss.tests.SSLClientAuth.main(SSLClientAuth.java:117)
java.io.IOException: SocketException cannot read on socket: Error reading from socket: (-12271) SSL peer cannot verify your certificate.
	at org.mozilla.jss.ssl.SSLSocket.read(SSLSocket.java:1511)
	at org.mozilla.jss.ssl.SSLInputStream.read(SSLInputStream.java:43)
	at org.mozilla.jss.ssl.SSLInputStream.read(SSLInputStream.java:28)
	at org.mozilla.jss.tests.SSLClientAuth.run(SSLClientAuth.java:464)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.mozilla.jss.ssl.SSLSocketException: Error reading from socket: (-12271) SSL peer cannot verify your certificate.
	at org.mozilla.jss.ssl.SSLSocket.socketRead(Native Method)
	at org.mozilla.jss.ssl.SSLSocket.read(SSLSocket.java:1505)
	... 4 more
Server exiting
```
https://github.com/dogtagpki/jss/runs/7506244588?check_suite_focus=true#step:7:2305
```
53/77 Test #53: SSLEngine_RSA .....................................***Failed    7.18 sec
Initializing CryptoManager...
Jul 25, 2022 6:27:34 PM org.mozilla.jss.CryptoManager initialize
INFO: JSS CryptoManager: successfully initialized from NSS database at /github/home/build/jss/results/nssdb
Jul 25, 2022 6:27:35 PM org.mozilla.jss.util.Password finalize
WARNING: Uncleared Password object created at org.mozilla.jss.JSSLoader.parsePasswords(JSSLoader.java:327)
        called by org.mozilla.jss.JSSLoader.init(JSSLoader.java:125)
        called by org.mozilla.jss.JSSLoader.init(JSSLoader.java:89)
        called by org.mozilla.jss.JSSProvider.configure(JSSProvider.java:77)
        called by java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:257)
        called by java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:248)
        called by java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        called by java.base/sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:248)
        called by java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:226)
        called by java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:268)
        called by java.base/sun.security.jca.ProviderList.getIndex(ProviderList.java:298)
        called by java.base/sun.security.jca.ProviderList.getProviderConfig(ProviderList.java:282)
        called by java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:288)
        called by java.base/java.security.Security.getProvider(Security.java:474)
        called by org.mozilla.jss.CryptoManager.getInstance(CryptoManager.java:395)
        called by org.mozilla.jss.tests.TestSSLEngine.initialize(TestSSLEngine.java:45)
        called by org.mozilla.jss.tests.TestSSLEngine.main(TestSSLEngine.java:1014)
Please report the above trace to your software vendors.
...
Jul 25, 2022 6:27:41 PM org.mozilla.jss.ssl.javax.JSSEngineReferenceImpl info
INFO: [JSS Client TLSv1.2/TLS_DHE_RSA_WITH_AES_128_CBC_SHA256] JSSEngine.unwrap() - Got SSLException: javax.net.ssl.SSLException: Unexpected return from PR.Read(): SSL_ERROR_HANDSHAKE_FAILED (-12116)
Error: Exception in thread "main" javax.net.ssl.SSLException: Unexpected return from PR.Read(): SSL_ERROR_HANDSHAKE_FAILED (-12116)
	at org.mozilla.jss.ssl.javax.JSSEngineReferenceImpl.unwrap(JSSEngineReferenceImpl.java:1259)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679)
	at org.mozilla.jss.tests.TestSSLEngine.testHandshake(TestSSLEngine.java:337)
	at org.mozilla.jss.tests.TestSSLEngine.testBasicHandshake(TestSSLEngine.java:779)
	at org.mozilla.jss.tests.TestSSLEngine.testAllHandshakes(TestSSLEngine.java:853)
	at org.mozilla.jss.tests.TestSSLEngine.testNativeClientServer(TestSSLEngine.java:1000)
	at org.mozilla.jss.tests.TestSSLEngine.main(TestSSLEngine.java:1029)
```

https://github.com/dogtagpki/jss/runs/7506244588?check_suite_focus=true#step:7:9650
```
60/77 Test #60: TestBufferPRFDSSL_RSA .............................***Failed    0.30 sec
error: SSL_ForceHandshake error -8010: SEC_ERROR_ALGORITHM_MISMATCH
Found cert with nickname: Server_RSA
Trying handshake...
Client Handshake:


Server Handshake:


Client Handshake:

      Start 61: TestBufferPRFDSSL_ECDSA
```

https://github.com/dogtagpki/jss/runs/7506244588?check_suite_focus=true#step:7:9665
```
62/77 Test #62: JSS_Test_BufferPRFD ...............................***Failed    0.68 sec
Calling TestCreateClose()...
Initializing CryptoManager...
Jul 25, 2022 6:27:45 PM org.mozilla.jss.CryptoManager initialize
INFO: JSS CryptoManager: successfully initialized from NSS database at /github/home/build/jss/results/nssdb
Calling TestSSLHandshake(Server_RSA, null)...
Initial: (TLS_1_2:32, TLS_1_3:35)
Actual: (TLS_1_2:32, TLS_1_3:35)
Initial: (TLS_1_2:32, TLS_1_3:35)
Actual: (TLS_1_2:32, TLS_1_3:35)
Unexpected error: SEC_ERROR_ALGORITHM_MISMATCH (-8010)
```

https://github.com/dogtagpki/jss/runs/7506244588?check_suite_focus=true#step:7:9686
```
67/77 Test #67: SSLClientAuth_FIPSMODE ............................***Failed    6.96 sec
Jul 25, 2022 6:27:53 PM org.mozilla.jss.CryptoManager initialize
INFO: JSS CryptoManager: successfully initialized from NSS database at /github/home/build/jss/results/fips
***FilePasswordCallback returns m1oZilla
using port:2877
The NSS database is configured in FIPSmode.
Enable ony FIPS ciphersuites.
Server about to create socket
Server created socket
Server specified cert directly
Server about to accept
client about to connect
Client specified cert directly
client connected
Server accepted
Server about to read
Error: Exception in thread "main" org.mozilla.jss.ssl.SSLSocketException: SSL_ForceHandshake failed: (-8010) Unknown error
	at org.mozilla.jss.ssl.SSLSocket.forceHandshake(Native Method)
	at org.mozilla.jss.tests.SSLClientAuth.testConnection(SSLClientAuth.java:372)
	at org.mozilla.jss.tests.SSLClientAuth.doIt(SSLClientAuth.java:183)
	at org.mozilla.jss.tests.SSLClientAuth.main(SSLClientAuth.java:117)
java.io.IOException: SocketException cannot read on socket: Error reading from socket: (-12271) SSL peer cannot verify your certificate.
	at org.mozilla.jss.ssl.SSLSocket.read(SSLSocket.java:1511)
	at org.mozilla.jss.ssl.SSLInputStream.read(SSLInputStream.java:43)
	at org.mozilla.jss.ssl.SSLInputStream.read(SSLInputStream.java:28)
	at org.mozilla.jss.tests.SSLClientAuth.run(SSLClientAuth.java:464)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.mozilla.jss.ssl.SSLSocketException: Error reading from socket: (-12271) SSL peer cannot verify your certificate.
	at org.mozilla.jss.ssl.SSLSocket.socketRead(Native Method)
	at org.mozilla.jss.ssl.SSLSocket.read(SSLSocket.java:1505)
	... 4 more
Server exiting
```

https://github.com/dogtagpki/jss/runs/7506244588?check_suite_focus=true#step:7:9728
````
72/77 Test #72: SSLEngine_RSA_FIPSMODE ............................***Failed    7.07 sec
Initializing CryptoManager...
Jul 25, 2022 6:28:08 PM org.mozilla.jss.CryptoManager initialize
INFO: JSS CryptoManager: successfully initialized from NSS database at /github/home/build/jss/results/fips
Jul 25, 2022 6:28:08 PM org.mozilla.jss.util.Password finalize
WARNING: Uncleared Password object created at org.mozilla.jss.JSSLoader.parsePasswords(JSSLoader.java:327)
        called by org.mozilla.jss.JSSLoader.init(JSSLoader.java:125)
        called by org.mozilla.jss.JSSLoader.init(JSSLoader.java:89)
        called by org.mozilla.jss.JSSProvider.configure(JSSProvider.java:77)
        called by java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:257)
        called by java.base/sun.security.jca.ProviderConfig$3.run(ProviderConfig.java:248)
        called by java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        called by java.base/sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:248)
        called by java.base/sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:226)
        called by java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:268)
        called by java.base/sun.security.jca.ProviderList.getIndex(ProviderList.java:298)
        called by java.base/sun.security.jca.ProviderList.getProviderConfig(ProviderList.java:282)
        called by java.base/sun.security.jca.ProviderList.getProvider(ProviderList.java:288)
        called by java.base/java.security.Security.getProvider(Security.java:474)
        called by org.mozilla.jss.CryptoManager.getInstance(CryptoManager.java:395)
        called by org.mozilla.jss.tests.TestSSLEngine.initialize(TestSSLEngine.java:45)
        called by org.mozilla.jss.tests.TestSSLEngine.main(TestSSLEngine.java:1014)
Please report the above trace to your software vendors.
...
INFO: [JSS Client TLSv1.2/TLS_DHE_RSA_WITH_AES_128_CBC_SHA256] JSSEngine.unwrap() - Got SSLException: javax.net.ssl.SSLException: Unexpected return from PR.Read(): SSL_ERROR_HANDSHAKE_FAILED (-12116)
Error: Exception in thread "main" javax.net.ssl.SSLException: Unexpected return from PR.Read(): SSL_ERROR_HANDSHAKE_FAILED (-12116)
	at org.mozilla.jss.ssl.javax.JSSEngineReferenceImpl.unwrap(JSSEngineReferenceImpl.java:1259)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679)
	at org.mozilla.jss.tests.TestSSLEngine.testHandshake(TestSSLEngine.java:337)
	at org.mozilla.jss.tests.TestSSLEngine.testBasicHandshake(TestSSLEngine.java:779)
	at org.mozilla.jss.tests.TestSSLEngine.testAllHandshakes(TestSSLEngine.java:853)
	at org.mozilla.jss.tests.TestSSLEngine.testNativeClientServer(TestSSLEngine.java:1000)
	at org.mozilla.jss.tests.TestSSLEngine.main(TestSSLEngine.java:1029)
```

**Comment by edewata** [comment]
@rjrelyea @jmagne Hi, are there major changes introduced in NSS 3.81? Is there anything we need to update in JSS?

**Comment by edewata** [comment]
The workaround has been reverted since it's causing COPR issues: https://github.com/dogtagpki/jss/pull/885

**Comment by rjrelyea** [comment]
Do these issue also happen on 3.79? (you reverted all the way back to 3.77). 3.79 is the current, about to be released NSS on RHEL-7.9, RHEL-8.6.0.z, RHEL-9.0.0.z

**Comment by edewata** [comment]
@rjrelyea For some reason `dnf` on F36 downgraded NSS 3.81 directly to 3.77. I'm not sure why it skipped 3.79.

**Comment by rjrelyea** [comment]
Can you test it on 3.79? there are 3.79 builds for F36. It would be important to check this. We are about to release NSSS 3.79 on RHEL 7.9, RHEL-8.6.0.z, and RHEL 9.0.0.z!

**Comment by edewata** [comment]
@rjrelyea I tried changing the dependency to NSS 3.79 explicitly:
https://github.com/edewata/jss/commit/bf111fdb8be5b22f1e37443740695eeca8020bf2
but it wouldn't install:
https://github.com/edewata/jss/runs/7734163817?check_suite_focus=true#step:4:1024
Was it released to F36?

Note: If you want to try yourself, just fork this project and push the changes like above to your forked project, and the CI should run automatically.

For RHEL you might want to coordinate the testing with IPA team. So far NSS 3.81 seems to be breaking JSS unit tests, but PKI seems to be unaffected. @rcritten?

**Comment by edewata** [comment]
I think @rcritten is on PTO. @abbra? ^^

**Comment by rcritten** [comment]
I've been testing on rawhide and was able to do a CA install using a softhsm token on Aug 5 with these packages:
nss-3.81.0-1.fc37.x86_64
dogtag-jss-5.2.0-1.fc37.1.x86_64
dogtag-pki-ca-11.2.0-2.fc37.noarch

The only changes I made were to dogtag itself, mostly in NSSDatabase class.

**Comment by rjrelyea** [comment]
rcritten: what were the NSSDatabase class changes?

**Comment by rcritten** [comment]
I don't mean to complicate things. I'm trying to get a PKI installation using softhsm2 as an HSM. The changes I made were mostly around wrapping some calls with runuser -u pkiuser so that FS permissions would be ok.

During this I also found https://bugzilla.mozilla.org/show_bug.cgi?id=1782980 which caused prompting for the token password during pkispawn.

Today I did an IPA install on F36 with pki 11.0.3 with my runuser changes both with and without softhsm2 and it was fine in that it installed and could issue certificates. Its very likely that I'm not exercising everything within NSS/JSS.

**Comment by ckelleyRH** [comment]
I was looking into this issue this morning.

It is curious that all the test failures are some variant of an SSL handshake failure except one - `JSS_Test_BufferPRFD` - so I dug into that first:
```
62/77 Test #62: JSS_Test_BufferPRFD ...............................***Failed    0.68 sec
Calling TestCreateClose()...
Initializing CryptoManager...
Jul 25, 2022 6:27:45 PM org.mozilla.jss.CryptoManager initialize
INFO: JSS CryptoManager: successfully initialized from NSS database at /github/home/build/jss/results/nssdb
Calling TestSSLHandshake(Server_RSA, null)...
Initial: (TLS_1_2:32, TLS_1_3:35)
Actual: (TLS_1_2:32, TLS_1_3:35)
Initial: (TLS_1_2:32, TLS_1_3:35)
Actual: (TLS_1_2:32, TLS_1_3:35)
Unexpected error: SEC_ERROR_ALGORITHM_MISMATCH (-8010)
```
It would appear here that there is some newly introduced TLS versioning issue in this test.

As we know `NSS 3.77` works for us, I went back through the [NSS release notes](https://firefox-source-docs.mozilla.org/security/nss/releases/nss_3_79.html) to look for a smoking gun. This [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1765753) concerning aborting handshakes for TLS 1.3 servers caught my eye.

If this bug fix did cause this issue then reverting to `NSS 3.79` will not save us, as the fix is introduced in that version.

I think the next test should be to try to build `NSS 3.81` with this fix reverted in a COPR repo and point the CI at it. If the CI goes green again happy days - we can set about figuring out what we're going to do about it.

**Comment by ckelleyRH** [comment]
I reverted to `NSS 3.79` and the issue goes away, so it is something added between 3.79 and 3.81.

**Comment by tjaalton** [comment]
So what about other distros? Just skip the tests? I've been stuck with 5.1 which now FTBFS's with openjdk-17, so I'll just shove 5.2 in bypassing the tests and hope this will get resolved at some point.

**Comment by ckelleyRH** [comment]
> So what about other distros? Just skip the tests? I've been stuck with 5.1 which now FTBFS's with openjdk-17, so I'll just shove 5.2 in bypassing the tests and hope this will get resolved at some point.

I've been skipping the tests locally but obviously that's not great. Sorry about the delay getting around to this, I have been fixing security issues. @fmarco76 has kindly volunteered to take a swing at this issue.
