### ISSUE TITLE
TPS test failed on Rawhide

### ISSUE THREAD

**Issue by edewata** [dogtagpki/jss#994]
The TPS test in JSS failed consistently on Rawhide:

https://github.com/edewata/jss/actions/runs/7821129758/job/21337674464#step:11:558

```
INFO: PKISocketFactory: Creating socket for pki.example.com:389
com.netscape.certsrv.base.PKIException: LDAP error (1): Operations error
	at com.netscape.certsrv.ldap.LDAPExceptionConverter.toPKIException(LDAPExceptionConverter.java:47)
	at com.netscape.cmscore.usrgrp.UGSubsystem.modifyGroup(UGSubsystem.java:1782)
	at org.dogtagpki.server.cli.SubsystemGroupMemberAddCLI.execute(SubsystemGroupMemberAddCLI.java:76)
	at org.dogtagpki.cli.CommandCLI.execute(CommandCLI.java:58)
	at org.dogtagpki.cli.CLI.execute(CLI.java:353)
	at org.dogtagpki.cli.CLI.execute(CLI.java:353)
	at org.dogtagpki.cli.CLI.execute(CLI.java:353)
	at org.dogtagpki.cli.CLI.execute(CLI.java:353)
	at org.dogtagpki.server.cli.PKIServerCLI.execute(PKIServerCLI.java:93)
	at org.dogtagpki.server.cli.PKIServerCLI.main(PKIServerCLI.java:123)
Caused by: netscape.ldap.LDAPException: Operations error (1)
	at netscape.ldap.LDAPConnection.checkMsg(LDAPConnection.java:4933)
	at netscape.ldap.LDAPConnection.modify(LDAPConnection.java:3201)
	at netscape.ldap.LDAPConnection.modify(LDAPConnection.java:3139)
	at netscape.ldap.LDAPConnection.modify(LDAPConnection.java:3149)
	at netscape.ldap.LDAPConnection.modify(LDAPConnection.java:3114)
	at com.netscape.cmscore.usrgrp.UGSubsystem.modifyGroup(UGSubsystem.java:1779)
	... 8 more
ERROR: CalledProcessError: Command '['/usr/sbin/runuser', '-u', 'pkiuser', '--', '/usr/lib/jvm/jre-17-openjdk/bin/java', '-classpath', '/usr/share/tomcat/bin/tomcat-juli.jar:/usr/share/java/tomcat-servlet-api.jar:/usr/share/pki/tks/webapps/tks/WEB-INF/lib/*:/var/lib/pki/pki-tomcat/common/lib/*:/usr/share/pki/lib/*', '-Djavax.sql.DataSource.Factory=org.apache.commons.dbcp.BasicDataSourceFactory', '-Dcatalina.base=/var/lib/pki/pki-tomcat', '-Dcatalina.home=/usr/share/tomcat', '-Djava.endorsed.dirs=', '-Djava.io.tmpdir=/var/lib/pki/pki-tomcat/temp', '-Djava.util.logging.config.file=/var/lib/pki/pki-tomcat/conf/logging.properties', '-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager', '-Dcom.redhat.fips=false', 'org.dogtagpki.server.cli.PKIServerCLI', 'tks-group-member-add', '--verbose', 'Administrators', 'tksadmin']' returned non-zero exit status 255.
  File "/usr/lib/python3.12/site-packages/pki/server/pkispawn.py", line 568, in main
    deployer.spawn()
  File "/usr/lib/python3.12/site-packages/pki/server/deployment/__init__.py", line 4985, in spawn
    scriptlet.spawn(self)
  File "/usr/lib/python3.12/site-packages/pki/server/deployment/scriptlets/configuration.py", line 191, in spawn
    deployer.setup_admin_user(subsystem, admin_cert)
  File "/usr/lib/python3.12/site-packages/pki/server/deployment/__init__.py", line 3934, in setup_admin_user
    subsystem.add_group_member(group, uid)
  File "/usr/lib/python3.12/site-packages/pki/server/subsystem.py", line 1837, in add_group_member
    self.run(cmd, as_current_user=as_current_user)
  File "/usr/lib/python3.12/site-packages/pki/server/subsystem.py", line 2210, in run
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
```

It is possible that the problem is actually somewhere else, not in JSS. This will require further investigation.

**Comment by edewata** [comment]
@fmarco76 @tbordaz @progier Apparently the above issue only happens using the DS packages from Fedora (including F40). See the following error log in DS:
https://github.com/dogtagpki/jss/actions/runs/10642850906/job/29505785149#step:22:148

```
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.883863746 +0000] - WARN - dbmdb_open_dbi_from_filename - Attempt to open to open dbi tks/description while txn is already pending. Usually that means that the index must be reindex. Root cause is likely that last import of reindex failed or that the index was created but not yet reindexed).
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.884950525 +0000] - WARN - slapi_log_backtrace -         [0]        /usr/lib64/dirsrv/libslapd.so.0(+0xf6138) [0x7fda9665c138]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.885301710 +0000] - WARN - slapi_log_backtrace -         [1]        /usr/lib64/dirsrv/plugins/libback-ldbm.so(dbmdb_open_dbi_from_filename+0x35a) [0x7fda91ef0a1a]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.885580180 +0000] - WARN - slapi_log_backtrace -         [2]        /usr/lib64/dirsrv/plugins/libback-ldbm.so(dbmdb_get_db+0xbc) [0x7fda91ef47fc]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.885903844 +0000] - WARN - slapi_log_backtrace -         [3]        /usr/lib64/dirsrv/plugins/libback-ldbm.so(dblayer_get_index_file+0xa8) [0x7fda91e78008]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.886220335 +0000] - WARN - slapi_log_backtrace -         [4]        /usr/lib64/dirsrv/plugins/libback-ldbm.so(index_addordel_values_ext_sv+0x155) [0x7fda91e8a315]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.886601236 +0000] - WARN - slapi_log_backtrace -         [5]        /usr/lib64/dirsrv/plugins/libback-ldbm.so(index_addordel_values_sv+0x18) [0x7fda91e8af58]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.886886379 +0000] - WARN - slapi_log_backtrace -         [6]        /usr/lib64/dirsrv/plugins/libback-ldbm.so(index_add_mods+0x680) [0x7fda91e8bc00]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.887236662 +0000] - WARN - slapi_log_backtrace -         [7]        /usr/lib64/dirsrv/plugins/libback-ldbm.so(ldbm_back_modify+0x850) [0x7fda91eaa500]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.887653240 +0000] - WARN - slapi_log_backtrace -         [8]        /usr/lib64/dirsrv/libslapd.so.0(+0x1023de) [0x7fda966683de]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.887972195 +0000] - WARN - slapi_log_backtrace -         [9]        /usr/lib64/dirsrv/libslapd.so.0(do_modify+0x99e) [0x7fda966697fe]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.888262517 +0000] - WARN - slapi_log_backtrace -         [10]        /usr/sbin/ns-slapd(+0x1c8db) [0x559e5d01e8db]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.888773251 +0000] - WARN - slapi_log_backtrace -         [11]        /lib64/libnspr4.so(+0x2b3b7) [0x7fda95c743b7]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.889107054 +0000] - WARN - slapi_log_backtrace -         [12]        /lib64/libc.so.6(+0x976d7) [0x7fda963fb6d7]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.889786903 +0000] - WARN - slapi_log_backtrace -         [13]        /lib64/libc.so.6(+0x11b60c) [0x7fda9647f60c]
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.890244087 +0000] - ERR - index_addordel_values_ext_sv - index_read NULL (could not open index attr description)
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.890748870 +0000] - ERR - index_addordel_values_ext_sv - database index operation failed BAD 1210, err=-30798 Unexpected dbimpl error code
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.891064185 +0000] - ERR - index_add_mods - database index operation failed BAD 1041, err=-30798 Unexpected dbimpl error code
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.891649888 +0000] - ERR - index_add_mods - database index operation failed BAD 1040, err=-30798 Unexpected dbimpl error code
Aug 31 05:49:35 ds.example.com ns-slapd[474]: [31/Aug/2024:05:49:35.892116139 +0000] - ERR - ldbm_back_modify - index_add_mods failed, err=-30798 Unexpected dbimpl error code
```

If we use the DS container from Quay the test will complete successfully without problem in DS:
https://github.com/dogtagpki/jss/actions/runs/10690850710/job/29636445358#step:23:9

Is this related to the DS issue reported in https://github.com/dogtagpki/pki/pull/4839?
